//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KryptonToolkitUpdater.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class UpdatePackageInformationSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UpdatePackageInformationSettings defaultInstance = ((UpdatePackageInformationSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UpdatePackageInformationSettings())));
        
        public static UpdatePackageInformationSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChangelogURL {
            get {
                return ((string)(this["ChangelogURL"]));
            }
            set {
                this["ChangelogURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentInstalledVersion {
            get {
                return ((string)(this["CurrentInstalledVersion"]));
            }
            set {
                this["CurrentInstalledVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DownloadURL {
            get {
                return ((string)(this["DownloadURL"]));
            }
            set {
                this["DownloadURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerVersion {
            get {
                return ((string)(this["ServerVersion"]));
            }
            set {
                this["ServerVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileName {
            get {
                return ((string)(this["FileName"]));
            }
            set {
                this["FileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MD5CheckSum {
            get {
                return ((string)(this["MD5CheckSum"]));
            }
            set {
                this["MD5CheckSum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SHA1CheckSum {
            get {
                return ((string)(this["SHA1CheckSum"]));
            }
            set {
                this["SHA1CheckSum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SHA256CheckSum {
            get {
                return ((string)(this["SHA256CheckSum"]));
            }
            set {
                this["SHA256CheckSum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SHA384CheckSum {
            get {
                return ((string)(this["SHA384CheckSum"]));
            }
            set {
                this["SHA384CheckSum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SHA512CheckSum {
            get {
                return ((string)(this["SHA512CheckSum"]));
            }
            set {
                this["SHA512CheckSum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RIPEMD160CheckSum {
            get {
                return ((string)(this["RIPEMD160CheckSum"]));
            }
            set {
                this["RIPEMD160CheckSum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VirusTotalURL {
            get {
                return ((string)(this["VirusTotalURL"]));
            }
            set {
                this["VirusTotalURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BetaFlag {
            get {
                return ((bool)(this["BetaFlag"]));
            }
            set {
                this["BetaFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UpdatePackageFileSize {
            get {
                return ((int)(this["UpdatePackageFileSize"]));
            }
            set {
                this["UpdatePackageFileSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime UpdatePackageBuildDate {
            get {
                return ((global::System.DateTime)(this["UpdatePackageBuildDate"]));
            }
            set {
                this["UpdatePackageBuildDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime UpdatePackageReleaseDate {
            get {
                return ((global::System.DateTime)(this["UpdatePackageReleaseDate"]));
            }
            set {
                this["UpdatePackageReleaseDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartUpdateInstallationUponDownloadCompletion {
            get {
                return ((bool)(this["StartUpdateInstallationUponDownloadCompletion"]));
            }
            set {
                this["StartUpdateInstallationUponDownloadCompletion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XMLUpdatePathURL {
            get {
                return ((string)(this["XMLUpdatePathURL"]));
            }
            set {
                this["XMLUpdatePathURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DownloadLocalLocation {
            get {
                return ((string)(this["DownloadLocalLocation"]));
            }
            set {
                this["DownloadLocalLocation"] = value;
            }
        }
    }
}
